### ss
# @ verbose
# 

{{

    function namegen() {
    const characters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    let result = '';
    const charactersLength = characters.length;
    for (let i = 0; i < 8; i++) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result
    }
    $global.usercn=namegen();
    $global.lastname=namegen();
}}
# @user-cn = Rama{{$randomInt 0001 9999}}

@usermail = {{user-cn}}@microsoft.com
POST {{SF-URL}}
SOAPAction : Login
Content-type: text/xml

<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope
    xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:urn="urn:partner.soap.sforce.com">
    <env:Header>
        <n1:CallOptions
            xmlns:n1="urn:partner.soap.sforce.com">
            <n1:client>SF-CLient</n1:client>
        </n1:CallOptions>
    </env:Header>
    <env:Body>
        <urn:login>
            <urn:username>{{SF-Admin-User}}</urn:username>
            <urn:password>{{SF-Admin-Pwd}}{{SF-Admin-Security-Token}}</urn:password>
        </urn:login>
    </env:Body>
</env:Envelope>

{{
const { parseStringPromise } = require('xml2js');
const fs = require('fs');
console.log(ss.response)
    try {
        // Parse the XML string into a JavaScript object
        const result = await parseStringPromise(ss);
        // console.log('Parsed XML structure:', JSON.stringify(result, null, 2));

        // Navigate through the parsed XML object to find the sessionId
        const sessionId = result?.['soapenv:Envelope']?.['soapenv:Body']?.[0]?.loginResponse?.[0]?.result?.[0]?.sessionId?.[0];
         $global.sessionId=sessionId
    } catch (error) {
        console.error('Error parsing XML:', error);
        throw error;
    }
}}

###
POST {{SF-Context-URL}}/services/Soap/u/52.0/{{SF-ProfileId}}
Content-type: text/xml
SOAPAction : POST

<soapenv:Envelope
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:urn="urn:partner.soap.sforce.com">
    <soapenv:Header>
        <urn:SessionHeader>
            <urn:sessionId>{{$global.sessionId }}</urn:sessionId>
        </urn:SessionHeader>
    </soapenv:Header>
<soapenv:Body>
    <urn:query>
        <urn:queryString>SELECT Username FROM User WHERE Email='mfotsfilm00018@mf-sf-testilm.com'</urn:queryString>
    </urn:query>
</soapenv:Body>undefined</soapenv:Envelope>

POST {{SF-Context-URL}}/services/Soap/u/52.0/{{SF-ProfileId}}
Content-type: text/xml
SOAPAction : POST

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:partner.soap.sforce.com" xmlns:urn1="urn:sobject.partner.soap.sforce.com">
        <soapenv:Header>
                <urn:SessionHeader>
                        <urn:sessionId>{{$global.sessionId }}</urn:sessionId>
                </urn:SessionHeader>
        </soapenv:Header>
        <soapenv:Body>
                <urn:create>
                        <urn:sObject>
                                <urn1:type>User</urn1:type>
                                <PostalCode>65001</PostalCode>
                                <State>Tamil Nadu</State>
                                <Street>340 VL Road</Street>
                                <LastName>{{$global.lastname}}</LastName>
                                <FirstName>{{$global.usercn}}</FirstName>
                                <Email>{{$global.usercn}}@microsoft.com</Email>
                                <Title>Expert</Title>
                                <Phone>9878765415</Phone>
                                <Alias>{{$global.usercn}}</Alias>
                                <Username>{{$global.usercn}}@microsoft.com</Username>
                                <ProfileId>00edL000003PgE8</ProfileId>
                                <TimeZoneSidKey>America/Los_Angeles</TimeZoneSidKey>
                                <EmailEncodingKey>UTF-8</EmailEncodingKey>
                                <LocaleSidKey>en_US</LocaleSidKey>
                                <LanguageLocaleKey>en_US</LanguageLocaleKey>
                        </urn:sObject>
                </urn:create>
        </soapenv:Body>
</soapenv:Envelope>
